
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed2;

	private global::Gtk.Button button3;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView txtBoxMetros1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView txtBoxCentimetros1;

	private global::Gtk.Label label6;

	private global::Gtk.Label label7;

	private global::Gtk.Label label8;

	private global::Gtk.Label label9;

	private global::Gtk.ScrolledWindow GtkScrolledWindow2;

	private global::Gtk.TextView txtBoxCentimetros2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow3;

	private global::Gtk.TextView txtBoxMetros2;

	private global::Gtk.Button btn2;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Gravity = ((global::Gdk.Gravity)(10));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed2 = new global::Gtk.Fixed();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("Convertir");
		this.fixed2.Add(this.button3);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.button3]));
		w1.X = 269;
		w1.Y = 59;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.txtBoxMetros1 = new global::Gtk.TextView();
		this.txtBoxMetros1.WidthRequest = 200;
		this.txtBoxMetros1.CanFocus = true;
		this.txtBoxMetros1.Name = "txtBoxMetros1";
		this.GtkScrolledWindow.Add(this.txtBoxMetros1);
		this.fixed2.Add(this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.GtkScrolledWindow]));
		w3.X = 40;
		w3.Y = 53;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.WidthRequest = 200;
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.txtBoxCentimetros1 = new global::Gtk.TextView();
		this.txtBoxCentimetros1.CanFocus = true;
		this.txtBoxCentimetros1.Name = "txtBoxCentimetros1";
		this.GtkScrolledWindow1.Add(this.txtBoxCentimetros1);
		this.fixed2.Add(this.GtkScrolledWindow1);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.GtkScrolledWindow1]));
		w5.X = 372;
		w5.Y = 52;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Metros");
		this.fixed2.Add(this.label6);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label6]));
		w6.X = 41;
		w6.Y = 18;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Centimetros");
		this.fixed2.Add(this.label7);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label7]));
		w7.X = 376;
		w7.Y = 18;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Centimetros");
		this.fixed2.Add(this.label8);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label8]));
		w8.X = 39;
		w8.Y = 196;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Metros");
		this.fixed2.Add(this.label9);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label9]));
		w9.X = 380;
		w9.Y = 188;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.txtBoxCentimetros2 = new global::Gtk.TextView();
		this.txtBoxCentimetros2.WidthRequest = 200;
		this.txtBoxCentimetros2.CanFocus = true;
		this.txtBoxCentimetros2.Name = "txtBoxCentimetros2";
		this.GtkScrolledWindow2.Add(this.txtBoxCentimetros2);
		this.fixed2.Add(this.GtkScrolledWindow2);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.GtkScrolledWindow2]));
		w11.X = 35;
		w11.Y = 231;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.txtBoxMetros2 = new global::Gtk.TextView();
		this.txtBoxMetros2.WidthRequest = 200;
		this.txtBoxMetros2.CanFocus = true;
		this.txtBoxMetros2.Name = "txtBoxMetros2";
		this.GtkScrolledWindow3.Add(this.txtBoxMetros2);
		this.fixed2.Add(this.GtkScrolledWindow3);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.GtkScrolledWindow3]));
		w13.X = 386;
		w13.Y = 224;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.btn2 = new global::Gtk.Button();
		this.btn2.CanFocus = true;
		this.btn2.Name = "btn2";
		this.btn2.UseUnderline = true;
		this.btn2.Label = global::Mono.Unix.Catalog.GetString("Convertir");
		this.fixed2.Add(this.btn2);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btn2]));
		w14.X = 273;
		w14.Y = 230;
		this.Add(this.fixed2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 620;
		this.DefaultHeight = 450;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button3.Clicked += new global::System.EventHandler(this.OnButton3Clicked);
		this.btn2.Clicked += new global::System.EventHandler(this.OnBtn2Clicked);
	}
}
